### ISSUE TITLE
Refused to execute script from https://raw.githubusercontent.com/...

### ISSUE THREAD

**Issue by burner1024** [ProgerXP/Orphus#1]
First off, thanks for resurrecting Orphus! I remember a time when most every site seemed to use it. It's a shame it's got abandoned.

It seems that the method from readme no longer works (in Chrome with default settings, at least):
`Refused to execute script from 'https://raw.githubusercontent.com/ProgerXP/Orphus/master/orphus-min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

As a workaround, self-hosted version works.

**Comment by ProgerXP** [comment]
> First off, thanks for resurrecting Orphus! I remember a time when most every site seemed to use it.

Yes, I was sold on its zero-configuration where you didn't even need a script to send mails. I'm surprised nobody used it as a spam relay back then. Those were the days...

> It seems that the method from readme no longer works (in Chrome with default settings, at least):

I'll have to replace this with a hotlink to my domain. Does the following work for you?

```
<script src="https://proger.me/orphus.js"></script>
```

**Comment by burner1024** [comment]
It worked when I tried it, although sending email through your domain didn't work, so I went for self-hosted php and js as well.

**Comment by ProgerXP** [comment]
I have fixed the URL, thanks for bringing this to my attention.

> It worked when I tried it, although sending email through your domain didn't work, so I went for self-hosted php and js as well.

I've just tested it and my script works. Perhaps you tried it in a very brief period when my site was down, but I didn't get any reports with domains other than my own. Anyway, self-hosted option is always better so I'm happy you made it working.
