### ISSUE TITLE
Не приходят сообщения

### ISSUE THREAD

**Issue by 1inkin** [ProgerXP/Orphus#3]
Здравствуйте. Скопировал папку Orphus-master на сайт, разместил в корне сайта файлы orphus.php (без изменений) и orphus-local.php (с указанием email, на который отправлять сообщения), в index.php прописал загрузку скрипта. В результате окно сообщения об ошибке появляется, после нажатия отправки браузер выводит сообщение "Thank you for the report.", но на почту ничего не приходит. В чем может быть проблема?

**Comment by ProgerXP** [comment]
В этот день приходило два письма на мою почту (`pizza-*.ru`). Проверьте, что форма делает запрос на ваш сервер, а не на мой (`action: 'https://proger.me/orphus.php'`, см. README).

Иначе проблема может быть в конфигурации почты PHP (функция `mail()` - настройки `sendmail_from` и другие). Обычно (но не всегда) она выдает предупреждения и их видно в логах сервера.

Для начала можете создать на сайте простейший скрипт с `<?php mail('your@self.ru', 'Subject...', 'Body');` - при его открытии в браузере вы должны получать письмо. Если это происходит, но `orphus.php` так и не работает - значит, проблема где-то на его стороне.

**Comment by 1inkin** [comment]
Скрипт `<?php mail('your@self.ru', 'Subject...', 'Body');` работает, сообщение пришло. В `orphus.js` по умолчанию параметр `action:         '/orphus.php'`, опять же, в файлах ничего не менял. В коде файлов не нашел упоминания `'https://proger.me/orphus.php'` кроме закомментированных частей. Файл `/orphus-local.php` скрипт вроде видит и считывает оттуда адрес электронной почты, потому что с ним при отправке в браузере сообщение `Thank you for the report.`, а без него `Unable to send the report.`. Но раз функция отправки срабатывает без ошибки и файл с указанием адреса считывается, то непонятно, куда сообщение уходит...

**Comment by ProgerXP** [comment]
Получается, 2 письма на мой адрес 25 числа были не от вас?

> потому что с ним при отправке в браузере сообщение `Thank you for the report.`, а без него `Unable to send the report.`.

Да, похоже у вас все работает как ожидается, кроме собственно отправки сообщения. Возможно, ваш почтовый сервер ведет себя необычно.

https://github.com/ProgerXP/Orphus/blob/93f91da4fa1086a3b3dbb7014acef707348fa6b4/orphus.php#L113-L117

Здесь видно, что `<?php mail('your@self.ru', 'Subject...', 'Body');` мало отличается от того, что делает скрипт. Попробуйте добавить в конец `orphus-local.php` вот это:

```
$mail = function () {
  mail('your@self.ru', 'Subject...', 'Body');
};
```

Если письмо придет (после отправки через форму), тогда замените на это:

```
// $to будет равно вашему адресу (из orphus-local.php)
// $subject = автоматический заголовок для письма
// $text = фрагмент с опечаткой
// $headers = системные заголовки
$mail = function ($to, $subject, $text, $headers) {
  // попробуйте так:
  mail($to, $subject, $text, $headers);
  // если не заработает (вероятно), тогда так:
  mail($to, $subject, $text);
  // потом так:
  mail('your@self.ru', $subject, $text, $headers);
  // потом так:
  mail('your@self.ru', $subject, $text);
  // потом так:
  mail('your@self.ru', 'Subject...', $text);
};
```

Я подозреваю, что проблема в значении `$to` или `$headers`. Если какой-то вариант выше заработает (т.е. письмо будет приходить), тогда напишите.

Так можно посмотреть, какие реальные значения используются для отправки письма:

```
$mail = function ($to, $subject, $text, $headers) {
  die('--><script>alert('.json_encode(var_export(func_get_args(), true)).')</script>');
};
```

**Comment by 1inkin** [comment]
после добавления в `orphus-local.php`
`$mail = function () {
  mail('your@self.ru', 'Subject...', 'Body');
};`
сообщение после отправки `Unable to send the report.` и на почту ничего не приходит. ни один из вариантов с `$mail = function (...` не сработал - везде `Unable to send the report.`. если в конце `orphus-local.php` добавить просто `mail('your@self.ru', 'Subject...', 'Body');`, тогда это дефолтное сообщение приходит, но не сообщение об ошибке, хотя показывает `Thank you for the report.`.

**Comment by 1inkin** [comment]
да, сработали только варианты, где не используется `$headers`

**Comment by ProgerXP** [comment]
> да, сработали только варианты, где не используется `$headers`

Надо же. Что у вас за почтовый сервер, если не секрет?

Я правильно понял, что если поместить в `orphus-local.php` вот это, то все начинает работать?

```
$mail = function ($to, $subject, $text, $headers) {
  mail($to, $subject, $text);
};
```

Если так, то ваша проблема решена, но для исправления скрипта мне нужно знать, сработает ли такой вариант:

```
$mail = function ($to, $subject, $text, $headers) {
  $headers = "Content-Type: text/plain; charset=utf-8\r\n".
             "Content-Transfer-Encoding: 8bit";
  mail($to, $subject, $text, $headers);
};
```

Если нет, то такой:

```
$mail = function ($to, $subject, $text, $headers) {
  $headers = "Content-Type: text/plain; charset=utf-8";
  mail($to, $subject, $text, $headers);
};
```

**Comment by 1inkin** [comment]
пользуюсь хостингом rucenter. стандартная конфигурация сервера с php 8, сам в настройки не лез. может, в php 8 какие-то изменения появились в функции mail?
> Я правильно понял, что если поместить в orphus-local.php вот это, то все начинает работать?

да, так работает.

> Если так, то ваша проблема решена, но для исправления скрипта мне нужно знать, сработает ли такой вариант:

работают оба варианта

**Comment by ProgerXP** [comment]
> может, в php 8 какие-то изменения появились в функции mail?

Маловероятно. В документации до сих пор указано, что иногда `\r\n` может обрабатываться неправильно, и я с этим лично сталкивался, а вот с `\n` проблем не встречал. Получается, у вас как раз с `\n` **не** работает, зато работает с `\r\n`.

Сделайте финальную проверку: работает ли, если поместить в `orphus-local.php` вот это?

```
$mail = function ($to, $subject, $text, $headers) {
  $headers = "Content-Type: text/plain; charset=utf-8\n".
             "Content-Transfer-Encoding: 8bit";
  mail($to, $subject, $text, $headers);
};
```

Если да, то я сделаю изменение в скрипте и вы сможете поменять простую настройку и не трогать функцию mail.

**Comment by 1inkin** [comment]
> вот это

это не работает

**Comment by ProgerXP** [comment]
Хорошо. Я обновил скрипт - обновите у себя `orphus.php`, а в `orphus-local.php` можете убрать `$mail = ...` и вместо этого вставить строку:

```
$eol = "\r\n";
```

**Comment by 1inkin** [comment]
> Я обновил скрипт

спасибо за помощь;)
